### ISSUE TITLE
[Feature Request] .crt name support

### ISSUE THREAD

**Issue by scmcgowen** [Allymonies/Radon#22]
I have actually finished the APIs and have the HTTP api ready for the CarrotPay Name Server
Documentation is available for the HTTP API [Here](https://docs.herrkatze.com/carrotpay/http_api/)

**Comment by Allymonies** [comment]
I'm hesitant to add this since it's untethered to krist, complicating multi-currency support, and is service specific rather than a standardized protocol, but I'll look into it regardless and see if there's a good way to implement this.

**Comment by scmcgowen** [comment]
I made a Krist-Compatible name_data endpoint specifically for your use case, just need to check if a name ends with .crt and if so, check the CarrotPay server. I plan on releasing the source code for it soon so other people could set one up for different currencies

**Comment by Allymonies** [comment]
Done in `1.3.34`, you can set the id to `carrotpay` to use `.crt` names instead of `.kst` names.
