### ISSUE TITLE
Chest indexing is slow

### ISSUE THREAD

**Issue by hugeblank** [Allymonies/Radon#3]
I'm running an enchanted book shop on SC3, every time I add a book to the products listing and reboot, the time it takes to refresh the index of items increases. It's to the point now that it takes about a minute for the shop to get indexed. Consider indexing all the chests using `parallel`.

**Comment by Allymonies** [comment]
I've parallelized inventory scanning by inventory in 1.3.2, let me know how it goes! If it's not too bad I'll consider this done, otherwise I may have to pursue more aggressive parallelization.
