### ISSUE TITLE
Question: how to make radon respect NBT?

### ISSUE THREAD

**Issue by MarcelDev** [Allymonies/Radon#6]

**Comment by hugeblank** [comment]
[Predicates](https://github.com/Allymonies/Radon/blob/54b1750fa741f40f4fdac7c756662bda4d9c7bab/products.lua#L44-L50).
If you specifically want to match on the NBT hash:
```
{
    modid = "minecraft:whatever",
    address = "whatever",
    price = 5,
    predicates = {
        nbt = "<insert nbt hash>"
    }
}
```

**Comment by MarcelDev** [comment]
> [Predicates](https://github.com/Allymonies/Radon/blob/54b1750fa741f40f4fdac7c756662bda4d9c7bab/products.lua#L44-L50). If you specifically want to match on the NBT hash:
> 
> ```
> {
>     modid = "minecraft:whatever",
>     address = "whatever",
>     price = 5,
>     predicates = {
>         nbt = "<insert nbt hash>"
>     }
> }
> ```

that was 4 months ago

**Comment by hugeblank** [comment]
https://github.com/Allymonies/Radon/blob/cd25c67aa8014d919de26d8072aeb6c166f0e183/products.lua#L44-L50
And here is predicates six months ago.

If your complaint was that you no longer needed help you should have closed this issue 👍
